# Generated by Django 2.2.6 on 2020-05-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200516_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='content',
            new_name='About_this_movie',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Your_Post_title',
            new_name='Your_Movie_Title',
        ),
    ]
