# Generated by Django 2.2.6 on 2020-05-16 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebs',
            fields=[
                ('Your_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('Your_Post_title', models.CharField(max_length=200)),
                ('Your_Post', models.TextField(max_length=2000)),
                ('Image', models.FileField(upload_to='profile_images')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Your_Post_title', models.CharField(max_length=2000)),
                ('id', models.CharField(max_length=5789, primary_key=True, serialize=False)),
                ('Your_name', models.CharField(max_length=900)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('Your_Post', models.TextField(max_length=909000)),
                ('Image', models.ImageField(null=True, upload_to='profile_image')),
                ('Your_Appreciation_or_Critics_about_this_movie', models.TextField(max_length=200000, null='True')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=42)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
